from app.models import db, Location

def seed_locations():
    locations = [
        {'user_id': 1,
        'street_address': '304 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78701,
        'lat': 30.262937,
        'long': -97.741687,
        'title': '',
        'description': 'Local legend!',
        'artist': ''},
        {'user_id': 12,
        'street_address': '2000 E Martin Luther King Jr Blvd',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.280313,
        'long': -97.719562,
        'title': '',
        'description': 'You\'re my butter half ❤️',
        'artist': 'Creative Suitcase'},
        {'user_id': 27,
        'street_address': '99 Waller St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.259563,
        'long': -97.732687,
        'title': '',
        'description': 'The girl in this mural has rad hair!',
        'artist': 'Roshi K'},
        {'user_id': 38,
        'street_address': '1209 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.259563,
        'long': -97.731938,
        'title': '',
        'description': 'I\'m a lover, not a fighter.',
        'artist': 'Federico Archuleta'},
        {'user_id': 41,
        'street_address': '2101 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.256062,
        'long': -97.721937,
        'title': '',
        'description': 'Selena will live forever',
        'artist': 'Federico Archuleta'},
        {'user_id': 19,
        'street_address': '1601 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.249063,
        'long': -97.755188,
        'title': '',
        'description': 'Loves Scotch!!',
        'artist': ''},
        {'user_id': 28,
        'street_address': '2209 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.243688,
        'long': -97.758062,
        'title': '',
        'description': 'A message of reflection',
        'artist': ''},
        {'user_id': 10,
        'street_address': '1821 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.246313,
        'long': -97.756438,
        'title': '',
        'description': 'Take that to the bank',
        'artist': ''},
        {'user_id': 5,
        'street_address': '1421 S Congress Ave',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.248938,
        'long': -97.749562,
        'title': 'Willie For President Mural',
        'description': 'Willie For President – In collaboration with Jacqui Oakley and Erick Montes.',
        'artist': 'Joe Swec'},
        {'user_id': 22,
        'street_address': 'South 1st Street',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.246437,
        'long': -97.756812,
        'title': '',
        'description': 'It\'s Becca...with the good hair..',
        'artist': ''},
        {'user_id': 37,
        'street_address': '1601 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.249063,
        'long': -97.754812,
        'title': '',
        'description': 'Alright Alright Alright – Located behind Criquet Shirts',
        'artist': 'Mez Data'},
        {'user_id': 42,
        'street_address': '198 Brazos St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78701,
        'lat': 30.26381152350619,
        'long': -97.7427833038301,
        'title': 'Tau Ceti',
        'description': 'This thing is a mind-blowing rainbow!',
        'artist': 'Josef Kristofoletti'},
        {'user_id': 4,
        'street_address': '7 E 51st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78723,
        'lat': 30.2998141619588,
        'long': -97.69339227441652,
        'title': 'Split Diopter',
        'description': 'These stacked ceramic blocks represent the simplified anatomy of a camera lens.',
        'artist': 'Eric Eley'},
        {'user_id': 50,
        'street_address': '4809 Bolm Rd',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.260883341642355,
        'long': -97.69439929719566,
        'title': 'Bolm Road',
        'description': 'Fourth generation East Austin artist Matthew Rodriguez creates playful imagery informed by conversations with residents of the Govalle neighborhood.',
        'artist': 'Matthew Briar Bonifacio Rodriguez'},
        {'user_id': 25,
        'street_address': 'Montopolis Youth Sports Complex, Grove Blvd',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.243060465682017,
        'long': -97.70070857127327,
        'title': 'Reach for Your Dreams',
        'description': 'This sculpture honors the children of Montopolis and the history of ball playing from the early Aztec ball players to Father Delaney, who helped start the neighborhood sports league.',
        'artist': 'Ambray Gonzalez'},
        {'user_id': 11,
        'street_address': '1900 E 12th St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.274143543040854,
        'long': -97.71978080210728,
        'title': 'We Rise',
        'description': '',
        'artist': 'Chris Rogers'},
        {'user_id': 17,
        'street_address': '408 W 21st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78705,
        'lat': 30.284079658290853,
        'long': -97.74212663820381,
        'title': 'Jeremiah the Innocent Mural',
        'description': 'An Austin classic on the Drag',
        'artist': 'Daniel Johnston'},
        {'user_id': 1,
        'street_address': '1816 E 6th St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.26193135497507,
        'long': -97.72276427276795,
        'title': 'Let\'s Band Together',
        'description': '',
        'artist': 'Federico Archuleta'},
        {'user_id': 31,
        'street_address': '1209 Red River St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78701,
        'lat': 30.272643,
        'long': -97.734388,
        'title': 'Spaceman with Floating Pizza',
        'description': '',
        'artist': 'Mike Johnston'},
        {'user_id': 24,
        'street_address': '90 Congress Ave',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78701,
        'lat': 30.262999,
        'long': -97.744637,
        'title': 'The Beauty of Liberty and Equality',
        'description': '',
        'artist': 'Sandra Chevrier, Shepard Fairey'},
        ]

    for location in locations:
        new_location = Location(**location)
        db.session.add(new_location)

    db.session.commit()


def undo_locations():
    db.session.execute('TRUNCATE locations RESTART IDENTITY CASCADE;')
    db.session.commit()
