from app.models import db, Location

def seed_locations():
    locations = [
        {'user_id': 1,
        'street_address': '304 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78701,
        'lat': 30.262937,
        'long': -97.741687,
        'title': '',
        'description': 'Local legend!',
        'artist': ''},
        {'user_id': 12,
        'street_address': '2000 E Martin Luther King Jr Blvd',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.280313,
        'long': -97.719562,
        'title': '',
        'description': 'You\'re my butter half ❤️',
        'artist': 'Creative Suitcase'},
        {'user_id': 27,
        'street_address': '99 Waller St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.259563,
        'long': -97.732687,
        'title': '',
        'description': 'This girl in this mural has rad hair!',
        'artist': 'Roshi K'},
        {'user_id': 38,
        'street_address': '1209 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.259563,
        'long': -97.731938,
        'title': '',
        'description': 'I\'m a lover, not a fighter.',
        'artist': 'Federico'},
        {'user_id': 41,
        'street_address': '2101 E Cesar Chavez St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78702,
        'lat': 30.256062,
        'long': -97.721937,
        'title': '',
        'description': 'Selena will live forever',
        'artist': 'Federico'},
        {'user_id': 19,
        'street_address': '1601 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.249063,
        'long': -97.755188,
        'title': '',
        'description': 'Loves Scotch!!',
        'artist': ''},
        {'user_id': 28,
        'street_address': '2209 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.243688,
        'long': -97.758062,
        'title': '',
        'description': 'A message of reflection',
        'artist': ''},
        {'user_id': 10,
        'street_address': '1821 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.246313,
        'long': -97.756438,
        'title': '',
        'description': 'Take that to the bank',
        'artist': ''},
        {'user_id': 5,
        'street_address': '1421 S Congress Ave',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.248938,
        'long': -97.749562,
        'title': 'Willie For President Mural',
        'description': 'Willie For President – In collaboration with Jacqui Oakley and Erick Montes.',
        'artist': 'Joe Swec'},
        {'user_id': 22,
        'street_address': 'South 1st Street',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.246437,
        'long': -97.756812,
        'title': '',
        'description': 'It\'s Becca...with the good hair..',
        'artist': ''},
        {'user_id': 37,
        'street_address': '1601 S 1st St',
        'city': 'Austin',
        'state': 'TX',
        'zip_code': 78704,
        'lat': 30.249063,
        'long': -97.754812,
        'title': '',
        'description': 'Alright Alright Alright – Located behind Criquet Shirts',
        'artist': 'Mez Data'}
        ]

    for location in locations:
        new_location = Location(**location)
        db.session.add(new_location)

    db.session.commit()


def undo_locations():
    db.session.execute('TRUNCATE locations RESTART IDENTITY CASCADE;')
    db.session.commit()
