"""empty message

Revision ID: b7368c0bf90c
Revises: a2700670d693
Create Date: 2021-02-22 18:06:40.692375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7368c0bf90c'
down_revision = 'a2700670d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###
