"""empty message

Revision ID: 20ba198e3958
Revises: e5faee5667df
Create Date: 2021-02-22 11:35:42.876358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ba198e3958'
down_revision = 'e5faee5667df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('locations', sa.Column('long', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'long')
    op.drop_column('locations', 'lat')
    # ### end Alembic commands ###
