"""empty message

Revision ID: 45ade33ec792
Revises: b7368c0bf90c
Create Date: 2021-02-22 21:13:05.050761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ade33ec792'
down_revision = 'b7368c0bf90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
