"""empty message

Revision ID: a2700670d693
Revises: 20ba198e3958
Create Date: 2021-02-22 17:47:46.531574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2700670d693'
down_revision = '20ba198e3958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_photo_id_fkey', 'locations', type_='foreignkey')
    op.drop_column('locations', 'photo_id')
    op.add_column('photos', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'photos', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'location_id')
    op.add_column('locations', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('locations_photo_id_fkey', 'locations', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###
